### ISSUE TITLE
only updating weekly?

### ISSUE THREAD

**Issue by jacobmar1ey** [igoralmeida/muzei-apod#3]
In on CM 13 with a Nexus 5 (hammerhead). The eclipse map was my background for like a week, now it's stuck on Annular Solar Eclipse over New Mexico. I've tried force stopping, clearing cache, clearing data, and restarting my phone. I can't get it to move forward. Even tried changing the photo source to the paintings and back but to no avail. Any suggestions?

**Comment by igoralmeida** [comment]
Interesting. Sometimes it won't update because a video crashes the parser, other times it is because Muzei is downloading a huge picture and does not show you any progress (or maybe it does but I didn't implement a way to be notified or fallback or whatever...). Be sure to check that you can visit http://apod.nasa.gov/apod/astropix.html on your phone.
If you can post (or send me) a logcat, it might help identifying what is going on.

**Comment by jacobmar1ey** [comment]
[bugreport-2016-09-08-05-07-31.zip](https://github.com/igoralmeida/muzei-apod/files/461862/bugreport-2016-09-08-05-07-31.zip)
I've attached the bug report from "Developer Options" though I'm not sure how useful it is though it is large.
It just updated last night to yesterday's photo but it isn't getting today's.

**Comment by igoralmeida** [comment]
I couldn't see anything suspicious, but I think it might be related to having the same permalink for all the images.
Changed the code a bit, will test for a couple of days and push if everything goes well.

**Comment by igoralmeida** [comment]
I've been testing for a while and couldn't see major problems. F-droid should pick it up in a day or two.
